baseurl = "https://ganlhi.github.io/csk-blog/"
title = "Centre Spatial de Kerbin"
languageCode = "fr-fr"
theme = "blackburn"

[Params]
  brand = "CSK"
  disqus = "Ganlhi"
  dateFormat = "02/01/2006"
  custom_css = ["css/custom.css"]

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Blog"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Le centre spatial"
    pre = "<i class='fa fa-building fa-fw'></i>"
    weight = 2
    identifier = "centre-spatial"
    url = "/centre-spatial/"
  [[menu.main]]
    name = "Vaisseaux et lanceurs"
    pre = "<i class='fa fa-rocket fa-fw'></i>"
    weight = 2
    identifier = "vaisseaux"
    url = "/vaisseaux/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  twitter = "ganlhi"

  # SNS photo/video sharing
  youtube = "https://www.youtube.com/playlist?list=PLZ16JLS5yHQeMzjU0Srz7Aq-VGeSciWuq"

  # Techie
  github = "ganlhi/csk"
